# Generated by Django 2.2.10 on 2023-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("villes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ville",
            name="departement",
            field=models.IntegerField(help_text="Departement de la ville.", null=True),
        ),
        migrations.AlterField(
            model_name="ville",
            name="code_insee",
            field=models.CharField(
                help_text="Code INSEE de la ville.", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ville",
            name="code_postal",
            field=models.CharField(
                help_text="Code postal de la ville.", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ville",
            name="nom",
            field=models.CharField(
                help_text="Nom de la ville.", max_length=256, null=True
            ),
        ),
    ]
