# Generated by Django 2.2.10 on 2023-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("villes", "0002_auto_20230302_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ville",
            name="departement",
            field=models.CharField(
                help_text="Departement de la ville.", max_length=128, null=True
            ),
        ),
    ]
